apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      serviceAccountName: test-rbac-sa
      containers:
      - name: test
        image: test:latest-x
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: test-rbac-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: test-rbac-role
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test-rbac-rolebinding
subjects:
- kind: ServiceAccount
  name: test-rbac-sa
  apiGroup: ""
roleRef:
  kind: Role
  name: test-rbac-role
  apiGroup: rbac.authorization.k8s.io

